In [1]:
from helpers import *

In [2]:
url = 'https://adventofcode.com/2021/day/1/input'
target_path = 'data/d1_data.txt'
download_data(url, target_path)

File already exist. Skipping download


In [3]:
bigger = 0

with open(target_path, 'r') as f:
    lines = f.readlines()
i = 0
for i in range(len(lines)):
    if i != 0:
        if int(lines[i].strip()) > int(lines[i-1].strip()):
            bigger += 1
    i += 1        
print(f"There is total of {len(lines)} meassurements. {bigger} is bigger than the previous one.")

There is total of 2000 meassurements. 1451 is bigger than the previous one.


<h3>Part 2 rolling window</h3>

In [4]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

In [5]:
vals = np.asarray([int(l.strip()) for l in lines])
vals

array([ 159,  170,  171, ..., 5877, 5878, 5881])

In [6]:
v = sliding_window_view(vals, 3)
v

array([[ 159,  170,  171],
       [ 170,  171,  170],
       [ 171,  170,  168],
       ...,
       [5877, 5878, 5877],
       [5878, 5877, 5878],
       [5877, 5878, 5881]])

In [7]:
summed = np.sum(v, axis = 1)
summed

array([  500,   511,   509, ..., 17632, 17633, 17636])

In [8]:
bigger = 0

for i in range(len(summed)):
    if i != 0:
        if summed[i] > summed[i-1]:
            bigger += 1
    i += 1        
print(f"There is total of {len(summed)} meassurements. {bigger} is bigger than the previous one.")

There is total of 1998 meassurements. 1395 is bigger than the previous one.
