In [1]:
from helpers import *
import numpy as np

In [2]:
data = get_data(4)
data[:10]

File already exist. Skipping download


['37,60,87,13,34,72,45,49,61,27,97,88,50,30,76,40,63,9,38,67,82,6,59,90,99,54,11,66,98,23,64,14,18,4,10,89,46,32,19,5,1,53,25,96,2,12,86,58,41,68,95,8,7,3,85,70,35,55,77,44,36,51,15,52,56,57,91,16,71,92,84,17,33,29,47,75,80,39,83,74,73,65,78,69,21,42,31,93,22,62,24,48,81,0,26,43,20,28,94,79\n',
 '\n',
 '66 78  7 45 92\n',
 '39 38 62 81 77\n',
 ' 9 73 25 97 99\n',
 '87 80 19  1 71\n',
 '85 35 52 26 68\n',
 '\n',
 '47 38 84 53 16\n',
 '66  3 63 92 94\n']

In [3]:
numbers = list(map(int, data[0].strip().split(',')))
numbers[-10:]

[24, 48, 81, 0, 26, 43, 20, 28, 94, 79]

In [4]:
boards = []
tmp = []
c = 0
for d in data:
    if len(d) == 15:
        tmp.append(d.strip().split())
        c += 1
        if c == 5:
            c = 0
            boards.append(np.asarray(tmp, dtype=np.int32))
            tmp = []
boards = np.array(boards)
boards_p2 = boards.copy()
boards.shape

(100, 5, 5)

In [5]:
winner = 0
for num in numbers:
    for board in boards:
        b = np.where(board == num)
        if len(b[0]) > 0:
            board[b[0], b[1]] = -1
        if any(np.sum(board, axis=0) == -5) or any(np.sum(board, axis=1) == -5):
            print(board)
            winner = np.sum((board != -1) * board) * num
            break
    if winner > 0:
        print(winner)
        break

[[-1 93 48 17 33]
 [-1  7  5  0 69]
 [-1 -1 52  1 -1]
 [-1 73 -1 25 16]
 [-1 20 41 77 62]]
34506


<h3>Part 2</h3>

In [6]:
scores = []
for num in numbers:
    winners = []
    for x, board in enumerate(boards_p2):
        winner = 0
        b = np.where(board == num)
        if len(b[0]) > 0:
            board[b[0], b[1]] = -1
        if any(np.sum(board, axis=0) == -5) or any(np.sum(board, axis=1) == -5):
            winner = np.sum((board != -1) * board) * num
            winners.append(x)
            scores.append(winner)
    if len(winners) > 0:
        boards_p2 = np.delete(boards_p2, winners, 0)

In [7]:
scores[-1]

7686